<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;

class MenProductsSeeder extends Seeder
{
    public function run(): void
    {
        $menCategory = Category::firstOrCreate(['slug' => 'men'], [
            'name' => 'Men',
            'image' => '/storage/categories/men.png',
            'is_active' => true,
        ]);

        $loomora = Brand::firstOrCreate(['slug' => 'loomora'], ['name' => 'Loomora', 'is_active' => true]);
        $dheu = Brand::firstOrCreate(['slug' => 'dheu'], ['name' => 'DHEU', 'is_active' => true]);
        $loomoraSignature = Brand::firstOrCreate(['slug' => 'loomora-signature'], ['name' => 'Loomora Signature', 'is_active' => true]);

        $brands = [
            'Loomora' => $loomora,
            'DHEU' => $dheu,
            'Loomora Signature' => $loomoraSignature,
        ];

        $subcategoriesList = [
            'Mens Polo' => 'mens-polo',
            'Mens Jeans Pant' => 'mens-jeans-pant',
            'Mens Formal Shirt' => 'mens-formal-shirt',
            'Mens Jacket' => 'mens-jacket',
            'Mens T-Shirt' => 'mens-t-shirt',
            'Mens Hoodie' => 'mens-hoodie',
            'Mens Sweatshirt' => 'mens-sweatshirt',
            'Mens Formal Pant' => 'mens-formal-pant',
            'Mens Shorts' => 'mens-shorts',
            'Mens Coti' => 'mens-coti',
            'Mens Joggers' => 'mens-joggers',
            'Mens Jersey' => 'mens-jersey',
            'Mens Chino Pant' => 'mens-chino-pant',
            'Mens Innerwear' => 'mens-innerwear',
            'Mens Biker Jacket' => 'mens-biker-jacket',
            'Mens Lungi' => 'mens-lungi',
            'Mens Overcoat' => 'mens-overcoat',
            'Mens Vest' => 'mens-vest',
            'Mens Katua & Fatua' => 'mens-katua-fatua',
            'Clothing & Fashion' => 'clothing-fashion',
        ];

        $subcategories = [];
        $order = 1;
        foreach ($subcategoriesList as $name => $slug) {
            $subcategories[$name] = Category::updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => $name,
                    'parent_id' => $menCategory->id,
                    'sort_order' => $order++,
                    'is_active' => true,
                ]
            );
        }

        $menCatalog = [
            [
                'name' => 'Mens Short Sleeves Polo Shirt - Slim Fit',
                'slug' => 'mens-short-sleeves-polo-shirt-slim-fit',
                'sku' => 'CLOTH-M01',
                'brand' => 'Loomora',
                'price' => 1290,
                'compare_price' => 1550,
                'image' => '/storage/products/men.avif',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => false,
                'sizes' => ['36', '38', '40', '42', '44'],
                'attributes' => [
                    'subcategory' => 'Mens Polo',
                    'category' => 'Mens Polo',
                    'fabric' => 'Cotton & Spandex',
                    'fit' => 'Slim Fit',
                    'sleeve' => 'Half Sleeve',
                    'neck' => 'Rib Collar',
                    'length' => 'Short',
                    'productType' => 'Polo',
                    'color' => '#6b7280',
                    'colorName' => 'Grey Melange',
                    'addition' => ['Embroidery'],
                    'festive' => ['Boishak 2026'],
                ],
            ],
            [
                'name' => 'Mens Sea Green Polo Shirt - Slim Fit',
                'slug' => 'mens-sea-green-polo-shirt-slim-fit',
                'sku' => 'CLOTH-M02-POLO',
                'brand' => 'Loomora',
                'price' => 1290,
                'compare_price' => 1500,
                'image' => '/storage/products/w-1.jpg',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => false,
                'sizes' => ['36', '38', '40', '42'],
                'attributes' => [
                    'subcategory' => 'Mens Polo',
                    'category' => 'Mens Polo',
                    'fabric' => 'Cotton & Lycra',
                    'fit' => 'Slim Fit',
                    'sleeve' => 'Half Sleeve',
                    'neck' => 'Rib Collar',
                    'length' => 'Short',
                    'productType' => 'Polo',
                    'color' => '#0f766e',
                    'colorName' => 'Sea Green',
                ],
            ],
            [
                'name' => 'Mens Dark Wash Denim Pant - Slim Fit',
                'slug' => 'mens-dark-wash-denim-pant-slim-fit',
                'sku' => 'CLOTH-M02',
                'brand' => 'DHEU',
                'price' => 1990,
                'compare_price' => 2390,
                'image' => '/storage/products/w-2.jpg',
                'badge' => 'Trending',
                'is_new_arrival' => false,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => true,
                'sizes' => ['30', '32', '34', '36'],
                'attributes' => [
                    'subcategory' => 'Mens Jeans Pant',
                    'category' => 'Mens Jeans Pant',
                    'fabric' => 'Denim',
                    'fit' => 'Slim Fit',
                    'length' => 'Full Length',
                    'productType' => 'Denim',
                    'color' => '#1e3a8a',
                    'colorName' => 'Dark Blue',
                ],
            ],
            [
                'name' => 'Mens Mid Light Wash Denim Pant - Regular Fit',
                'slug' => 'mens-mid-light-wash-denim-pant-regular-fit',
                'sku' => 'CLOTH-M04',
                'brand' => 'Loomora',
                'price' => 1290,
                'compare_price' => 1650,
                'image' => '/storage/products/w-3.jpg',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => false,
                'is_hot' => false,
                'is_trending' => false,
                'sizes' => ['30', '32', '34', '36'],
                'attributes' => [
                    'subcategory' => 'Mens Jeans Pant',
                    'category' => 'Mens Jeans Pant',
                    'fabric' => 'Denim',
                    'fit' => 'Regular Fit',
                    'length' => 'Full Length',
                    'productType' => 'Denim',
                    'color' => '#475569',
                    'colorName' => 'Slate Grey',
                ],
            ],
            [
                'name' => 'Mens Sky Blue Wash Denim Pant - Regular Fit',
                'slug' => 'mens-sky-blue-wash-denim-pant-regular-fit',
                'sku' => 'CLOTH-M05',
                'brand' => 'DHEU',
                'price' => 1390,
                'compare_price' => 1750,
                'image' => '/storage/products/w-4.jpg',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => false,
                'is_hot' => false,
                'is_trending' => false,
                'sizes' => ['30', '32', '34', '36'],
                'attributes' => [
                    'subcategory' => 'Mens Jeans Pant',
                    'category' => 'Mens Jeans Pant',
                    'fabric' => 'Denim',
                    'fit' => 'Regular Fit',
                    'length' => 'Full Length',
                    'productType' => 'Denim',
                    'color' => '#0284c7',
                    'colorName' => 'Sky Blue',
                ],
            ],
            [
                'name' => 'Mens Premium Rust Bomber Jacket - Regular Fit',
                'slug' => 'mens-premium-rust-bomber-jacket-regular-fit',
                'sku' => 'CLOTH-M06',
                'brand' => 'Loomora',
                'price' => 2000,
                'compare_price' => 2500,
                'image' => '/storage/products/c-1.png',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => true,
                'is_hot' => true,
                'is_trending' => false,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'attributes' => [
                    'subcategory' => 'Mens Jacket',
                    'category' => 'Mens Jacket',
                    'fabric' => 'Bamboo Fiber & Synthetic',
                    'fit' => 'Regular Fit',
                    'sleeve' => 'Full Sleeve',
                    'length' => 'Full Length',
                    'productType' => 'Jacket',
                    'color' => '#b45309',
                    'colorName' => 'Rust Brown',
                ],
            ],
            [
                'name' => 'Mens Crimson Velvet Formal Blazer',
                'slug' => 'mens-crimson-velvet-formal-blazer',
                'sku' => 'CLOTH-M07',
                'brand' => 'Loomora Signature',
                'price' => 4500,
                'compare_price' => 5200,
                'image' => '/storage/products/c-6.png',
                'badge' => 'Exclusive',
                'is_new_arrival' => false,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => true,
                'sizes' => ['38', '40', '42'],
                'attributes' => [
                    'subcategory' => 'Mens Jacket',
                    'category' => 'Mens Jacket',
                    'fabric' => 'Velvet',
                    'fit' => 'Slim Fit',
                    'sleeve' => 'Full Sleeve',
                    'neck' => 'Collar',
                    'length' => 'Full Length',
                    'productType' => 'Blazer',
                    'color' => '#dc2626',
                    'colorName' => 'Crimson Red',
                    'festive' => ['Eid 2026', 'Puja 2026'],
                ],
            ],
            [
                'name' => 'Mens Crisp Pure Egyptian Cotton White Shirt',
                'slug' => 'mens-crisp-pure-egyptian-cotton-white-shirt',
                'sku' => 'CLOTH-M08',
                'brand' => 'Loomora',
                'price' => 1750,
                'compare_price' => 2100,
                'image' => '/storage/products/c-9.png',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => false,
                'sizes' => ['38', '40', '42', '44'],
                'attributes' => [
                    'subcategory' => 'Mens Formal Shirt',
                    'category' => 'Mens Formal Shirt',
                    'fabric' => 'Cotton jacquard Shirting Fabric',
                    'fit' => 'Regular Fit',
                    'sleeve' => 'Full Sleeve',
                    'neck' => 'Collar',
                    'length' => 'Full Length',
                    'productType' => 'Shirt',
                    'color' => '#ffffff',
                    'colorName' => 'White',
                    'festive' => ['Eid 2026'],
                ],
            ],
            [
                'name' => 'Mens Classic Denim Trucker Jacket',
                'slug' => 'mens-classic-denim-trucker-jacket',
                'sku' => 'CLOTH-M09',
                'brand' => 'DHEU',
                'price' => 2199,
                'compare_price' => 2600,
                'image' => '/storage/products/c-3.png',
                'badge' => 'New',
                'is_new_arrival' => false,
                'is_featured' => true,
                'is_hot' => true,
                'is_trending' => false,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'attributes' => [
                    'subcategory' => 'Mens Jacket',
                    'category' => 'Mens Jacket',
                    'fabric' => 'Denim',
                    'fit' => 'Regular Fit',
                    'sleeve' => 'Full Sleeve',
                    'neck' => 'Collar',
                    'length' => 'Full Length',
                    'productType' => 'Denim',
                    'color' => '#1e3a8a',
                    'colorName' => 'Classic Denim',
                ],
            ],
            [
                'name' => 'Mens Heather Grey Cotton Crewneck Tee',
                'slug' => 'mens-heather-grey-cotton-crewneck-tee',
                'sku' => 'CLOTH-M10',
                'brand' => 'Loomora',
                'price' => 890,
                'compare_price' => 1100,
                'image' => '/storage/products/c-7.png',
                'badge' => 'Best Value',
                'is_new_arrival' => false,
                'is_featured' => false,
                'is_hot' => true,
                'is_trending' => true,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'attributes' => [
                    'subcategory' => 'Mens T-Shirt',
                    'category' => 'Mens T-Shirt',
                    'fabric' => 'Cotton',
                    'fit' => 'Regular Fit',
                    'sleeve' => 'Half Sleeve',
                    'neck' => 'Round',
                    'length' => 'Short',
                    'productType' => 'T-Shirt',
                    'color' => '#71717a',
                    'colorName' => 'Grey',
                ],
            ],
            [
                'name' => 'Mens Navy Fleece Hoodie & Denim Set',
                'slug' => 'mens-navy-fleece-hoodie-denim-set',
                'sku' => 'CLOTH-M11',
                'brand' => 'Loomora',
                'price' => 1224,
                'compare_price' => 1360,
                'image' => '/storage/products/c-8.png',
                'badge' => 'Hot Deal',
                'is_new_arrival' => false,
                'is_featured' => true,
                'is_hot' => true,
                'is_trending' => false,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'attributes' => [
                    'subcategory' => 'Mens Hoodie',
                    'category' => 'Mens Hoodie',
                    'fabric' => 'Fleece',
                    'fit' => 'Over-sized',
                    'sleeve' => 'Full Sleeve',
                    'neck' => 'Hooded Neck',
                    'length' => 'Long',
                    'productType' => 'Hoodie',
                    'color' => '#12509b',
                    'colorName' => 'Navy',
                    'addition' => ['Print'],
                    'set' => '2pcs',
                ],
            ],
            [
                'name' => 'Mens Everyday Fleece Relaxed Sweatshirt',
                'slug' => 'mens-everyday-fleece-relaxed-sweatshirt',
                'sku' => 'CLOTH-M12',
                'brand' => 'Loomora',
                'price' => 1650,
                'compare_price' => 1990,
                'image' => '/storage/products/c-2.png',
                'badge' => 'New',
                'is_new_arrival' => true,
                'is_featured' => true,
                'is_hot' => false,
                'is_trending' => true,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'attributes' => [
                    'subcategory' => 'Mens Sweatshirt',
                    'category' => 'Mens Sweatshirt',
                    'fabric' => 'Fleece Fabric',
                    'fit' => 'Boxy Fit',
                    'sleeve' => 'Full Sleeve',
                    'neck' => 'Round',
                    'length' => 'Long',
                    'productType' => 'Sweatshirt',
                    'color' => '#f5f5f4',
                    'colorName' => 'Off White',
                ],
            ],
        ];

        foreach ($menCatalog as $item) {
            $brand = $brands[$item['brand']] ?? $loomora;
            $targetSubcategory = $subcategories[$item['attributes']['category']] ?? $menCategory;

            $product = Product::updateOrCreate(
                ['sku' => $item['sku']],
                [
                    'name' => $item['name'],
                    'slug' => $item['slug'],
                    'category_id' => $targetSubcategory->id,
                    'brand_id' => $brand->id,
                    'product_type' => 'apparel',
                    'price' => $item['price'],
                    'compare_price' => $item['compare_price'],
                    'cost_price' => round($item['price'] * 0.55, 2),
                    'stock_quantity' => 100,
                    'low_stock_threshold' => 10,
                    'status' => 'published',
                    'is_featured' => $item['is_featured'],
                    'is_new_arrival' => $item['is_new_arrival'],
                    'is_hot' => $item['is_hot'],
                    'is_trending' => $item['is_trending'],
                    'badge_label' => $item['badge'],
                    'primary_image' => $item['image'],
                    'short_description' => "Premium {$item['name']} by {$item['brand']}.",
                    'description' => "Crafted from {$item['attributes']['fabric']}. Designed for exceptional comfort and lasting quality.",
                    'attributes' => $item['attributes'],
                    'has_variants' => count($item['sizes']) > 0,
                ]
            );

            // Re-sync variants
            ProductVariant::where('product_id', $product->id)->delete();
            foreach ($item['sizes'] as $size) {
                ProductVariant::create([
                    'product_id' => $product->id,
                    'sku' => "{$item['sku']}-{$size}",
                    'price' => $item['price'],
                    'compare_price' => $item['compare_price'],
                    'cost_price' => round($item['price'] * 0.55, 2),
                    'stock_quantity' => 25,
                    'option_values' => ['size' => $size],
                    'is_active' => true,
                ]);
            }
        }
    }
}
